#!/bin/sh

set -x

BUILD_TYPE=$1

cmake \
    -S DJV \
    -B build-$BUILD_TYPE \
    -DDJV_MACOS_PACKAGE=ON \
    -DDJV_MACOS_TEAM_ID=$DJV_MACOS_TEAM_ID \
    -DTLRENDER_NET=$TLRENDER_NET \
    -DTLRENDER_OCIO=$TLRENDER_OCIO \
    -DTLRENDER_EXR=$TLRENDER_EXR \
    -DTLRENDER_FFMPEG=$TLRENDER_FFMPEG \
    -DTLRENDER_OIIO=$TLRENDER_OIIO \
    -DTLRENDER_USD=$TLRENDER_USD \
    -DTLRENDER_BMD=$TLRENDER_BMD \
    -Dftk_API=$FTK_API \
    -DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS \
    -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
    -DCMAKE_INSTALL_PREFIX=$PWD/install-$BUILD_TYPE \
    -DCMAKE_PREFIX_PATH=$PWD/install-$BUILD_TYPE \
    -DCMAKE_OSX_DEPLOYMENT_TARGET=$CMAKE_OSX_DEPLOYMENT_TARGET \
    -DCMAKE_OSX_ARCHITECTURES=$CMAKE_OSX_ARCHITECTURES
cmake --build build-$BUILD_TYPE -j $JOBS --config $BUILD_TYPE
cmake --build build-$BUILD_TYPE --config $BUILD_TYPE --target package
