#!/bin/sh

set -x

SOURCE_DIR=$1
BUILD_TYPE=$2

git -C $SOURCE_DIR submodule update --init --recursive

cmake \
    -S $SOURCE_DIR/deps/tlRender/deps/ftk/etc/SuperBuild \
    -B ftk-$BUILD_TYPE \
    -Dftk_PYTHON=$TLRENDER_PYTHON \
    -DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS \
    -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
    -DCMAKE_INSTALL_PREFIX=$PWD/install-$BUILD_TYPE \
    -DCMAKE_PREFIX_PATH=$PWD/install-$BUILD_TYPE \
    -DCMAKE_OSX_DEPLOYMENT_TARGET=$CMAKE_OSX_DEPLOYMENT_TARGET \
    -DCMAKE_OSX_ARCHITECTURES=$CMAKE_OSX_ARCHITECTURES
cmake --build ftk-$BUILD_TYPE -j $JOBS --config $BUILD_TYPE

cmake \
    -S $SOURCE_DIR/deps/tlRender/etc/SuperBuild \
    -B tl-$BUILD_TYPE \
    -DTLRENDER_NET=$TLRENDER_NET \
    -DTLRENDER_OCIO=$TLRENDER_OCIO \
    -DTLRENDER_JPEG=$TLRENDER_JPEG \
    -DTLRENDER_TIFF=$TLRENDER_TIFF \
    -DTLRENDER_EXR=$TLRENDER_EXR \
    -DTLRENDER_AOM=$TLRENDER_AOM \
    -DTLRENDER_SVTAV1=$TLRENDER_SVTAV1 \
    -DTLRENDER_FFMPEG=$TLRENDER_FFMPEG \
    -DTLRENDER_FFMPEG_MINIMAL=$TLRENDER_FFMPEG_MINIMAL \
    -DTLRENDER_FFMPEG_PLUGIN=$TLRENDER_FFMPEG_PLUGIN \
    -DTLRENDER_FFMPEG_CMD=$TLRENDER_FFMPEG_CMD \
    -DTLRENDER_NASM=$TLRENDER_NASM \
    -DTLRENDER_OIIO=$TLRENDER_OIIO \
    -DTLRENDER_USD=$TLRENDER_USD \
    -DTLRENDER_PYTHON=$TLRENDER_PYTHON \
    -DTLRENDER_PROGRAMS=$TLRENDER_PROGRAMS \
    -DTLRENDER_EXAMPLES=$TLRENDER_EXAMPLES \
    -DTLRENDER_TESTS=$TLRENDER_TESTS \
    -Dftk_API=$FTK_API \
    -Dftk_EXAMPLES=$FTK_EXAMPLES \
    -Dftk_TESTS=$FTK_TESTS \
    -DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS \
    -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
    -DCMAKE_INSTALL_PREFIX=$PWD/install-$BUILD_TYPE \
    -DCMAKE_PREFIX_PATH=$PWD/install-$BUILD_TYPE \
    -DCMAKE_OSX_DEPLOYMENT_TARGET=$CMAKE_OSX_DEPLOYMENT_TARGET \
    -DCMAKE_OSX_ARCHITECTURES=$CMAKE_OSX_ARCHITECTURES
cmake --build tl-$BUILD_TYPE -j $JOBS --config $BUILD_TYPE

cmake \
    -S $SOURCE_DIR \
    -B build-$BUILD_TYPE \
    -DDJV_TESTS=$DJV_TESTS \
    -DDJV_MACOS_PACKAGE=OFF \
    -DDJV_MACOS_TEAM_ID=$DJV_MACOS_TEAM_ID \
    -DTLRENDER_NET=$TLRENDER_NET \
    -DTLRENDER_OCIO=$TLRENDER_OCIO \
    -DTLRENDER_EXR=$TLRENDER_EXR \
    -DTLRENDER_AOM=$TLRENDER_AOM \
    -DTLRENDER_SVTAV1=$TLRENDER_SVTAV1 \
    -DTLRENDER_FFMPEG=$TLRENDER_FFMPEG \
    -DTLRENDER_FFMPEG_PLUGIN=$TLRENDER_FFMPEG_PLUGIN \
    -DTLRENDER_FFMPEG_CMD=$TLRENDER_FFMPEG_CMD \
    -DTLRENDER_NASM=$TLRENDER_NASM \
    -DTLRENDER_OIIO=$TLRENDER_OIIO \
    -DTLRENDER_USD=$TLRENDER_USD \
    -DTLRENDER_PYTHON=$TLRENDER_PYTHON \
    -Dftk_API=$FTK_API \
    -Dftk_PYTHON=$TLRENDER_PYTHON \
    -DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS \
    -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
    -DCMAKE_INSTALL_PREFIX=$PWD/install-$BUILD_TYPE \
    -DCMAKE_PREFIX_PATH=$PWD/install-$BUILD_TYPE \
    -DCMAKE_OSX_DEPLOYMENT_TARGET=$CMAKE_OSX_DEPLOYMENT_TARGET \
    -DCMAKE_OSX_ARCHITECTURES=$CMAKE_OSX_ARCHITECTURES
cmake --build build-$BUILD_TYPE -j $JOBS --config $BUILD_TYPE

if [ "$DJV_TESTS" = "ON" ]; then
    (cd build-$BUILD_TYPE && ctest --output-on-failure -C $BUILD_TYPE)
fi
