#!/bin/sh

set -x

SOURCE_DIR=$1
BUILD_TYPE=$2

cmake \
    -S $SOURCE_DIR \
    -B build-$BUILD_TYPE \
    -DTLRENDER_NET=$TLRENDER_NET \
    -DTLRENDER_OCIO=$TLRENDER_OCIO \
    -DTLRENDER_EXR=$TLRENDER_EXR \
    -DTLRENDER_AOM=$TLRENDER_AOM \
    -DTLRENDER_STAV1=$TLRENDER_STAV1 \
    -DTLRENDER_FFMPEG=$TLRENDER_FFMPEG \
    -DTLRENDER_FFMPEG_PLUGIN=$TLRENDER_FFMPEG_PLUGIN \
    -DTLRENDER_FFMPEG_CMD=$TLRENDER_FFMPEG_CMD \
    -DTLRENDER_NASM=$TLRENDER_NASM \
    -DTLRENDER_OIIO=$TLRENDER_OIIO \
    -DTLRENDER_USD=$TLRENDER_USD \
    -Dftk_API=$FTK_API \
    -DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS \
    -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
    -DCMAKE_INSTALL_PREFIX=$PWD/install-$BUILD_TYPE \
    -DCMAKE_PREFIX_PATH=$PWD/install-$BUILD_TYPE
cmake --build build-$BUILD_TYPE -j $JOBS --config $BUILD_TYPE
cmake --build build-$BUILD_TYPE --config $BUILD_TYPE --target package
