set SOURCE_DIR=%1

set JOBS=4
set DJV_TESTS=OFF
set TLRENDER_NET=OFF
set TLRENDER_OCIO=ON
set TLRENDER_JPEG=ON
set TLRENDER_TIFF=ON
set TLRENDER_EXR=ON
set TLRENDER_AOM=OFF
set TLRENDER_SVTAV1=OFF
set TLRENDER_FFMPEG=ON
set TLRENDER_FFMPEG_MINIMAL=ON
set TLRENDER_FFMPEG_PLUGIN=ON
set TLRENDER_FFMPEG_CMD=ON
set TLRENDER_NASM=OFF
set TLRENDER_OIIO=ON
set TLRENDER_USD=OFF
set TLRENDER_PYTHON=OFF
set TLRENDER_PROGRAMS=OFF
set TLRENDER_EXAMPLES=OFF
set TLRENDER_TESTS=OFF
set FTK_API=GL_4_1
set FTK_EXAMPLES=OFF
set FTK_TESTS=OFF
set BUILD_SHARED_LIBS=OFF

call %SOURCE_DIR%\etc\Windows\sbuild.bat %SOURCE_DIR% Release
cmake --build build-Release --config Release --target package
