set SOURCE_DIR=%1

set JOBS=4
set TLRENDER_NET=OFF
set TLRENDER_OCIO=ON
set TLRENDER_JPEG=ON
set TLRENDER_TIFF=ON
set TLRENDER_EXR=ON
set TLRENDER_AOM=ON
set TLRENDER_SVTAV1=ON
set TLRENDER_FFMPEG=ON
set TLRENDER_FFMPEG_MINIMAL=ON
set TLRENDER_FFMPEG_PLUGIN=ON
set TLRENDER_FFMPEG_CMD=ON
set TLRENDER_NASM=OFF
set TLRENDER_OIIO=ON
set TLRENDER_USD=OFF
set FTK_API=GL_4_1

call %SOURCE_DIR%\etc\Windows\windows-sbuild.bat %SOURCE_DIR% Release
call %SOURCE_DIR%\etc\Windows\windows-package.bat %SOURCE_DIR% Release
