#!/bin/sh

set -x

SOURCE_DIR=$1

export JOBS=4
export TLRENDER_NET=OFF
export TLRENDER_OCIO=ON
export TLRENDER_JPEG=ON
export TLRENDER_TIFF=ON
export TLRENDER_EXR=ON
export TLRENDER_AOM=ON
export TLRENDER_SVTAV1=ON
export TLRENDER_FFMPEG=ON
export TLRENDER_FFMPEG_MINIMAL=ON
export TLRENDER_FFMPEG_PLUGIN=ON
export TLRENDER_FFMPEG_CMD=ON
export TLRENDER_NASM=ON
export TLRENDER_OIIO=ON
export TLRENDER_USD=OFF
export FTK_API=GL_4_1
export CMAKE_OSX_DEPLOYMENT_TARGET=10.15
export CMAKE_OSX_ARCHITECTURES=arm64

sh $SOURCE_DIR/etc/macOS/macos-sbuild.sh $SOURCE_DIR Release
sh $SOURCE_DIR/etc/macOS/macos-package.sh $SOURCE_DIR Release
