set TLRENDER_NET=OFF
set TLRENDER_OCIO=ON
set TLRENDER_JPEG=ON
set TLRENDER_TIFF=ON
set TLRENDER_EXR=ON
set TLRENDER_FFMPEG=ON
set TLRENDER_FFMPEG_MINIMAL=ON
set TLRENDER_OIIO=ON
set TLRENDER_USD=ON
set TLRENDER_BMD=OFF
set TLRENDER_BMD_SDK=
set FTK_API=GL_4_1

call DJV\etc\Windows\windows-sbuild.bat Release
call DJV\etc\Windows\windows-package.bat Release
