set BUILD_TYPE=%1
IF "%BUILD_TYPE%"=="" set BUILD_TYPE=Release

set JOBS=4
set TLRENDER_NET=OFF
set TLRENDER_OCIO=ON
set TLRENDER_JPEG=ON
set TLRENDER_TIFF=ON
set TLRENDER_EXR=ON
set TLRENDER_FFMPEG=ON
set TLRENDER_FFMPEG_MINIMAL=ON
set TLRENDER_FFMPEG_PLUGIN=OFF
set TLRENDER_FFMPEG_PIPE=ON
set TLRENDER_NASM=OFF
set TLRENDER_OIIO=ON
set TLRENDER_USD=OFF
set TLRENDER_BMD=OFF
set TLRENDER_BMD_SDK=
set FTK_API=GL_4_1
set BUILD_SHARED_LIBS=OFF

call DJV\etc\Windows\windows-sbuild.bat %BUILD_TYPE%
call DJV\etc\Windows\windows-build.bat %BUILD_TYPE%
