set SOURCE_DIR=%1
set BUILD_TYPE=%2

cmake ^
    -S %SOURCE_DIR% ^
    -B build-%BUILD_TYPE% ^
    -DDJV_WINDOWS_PACKAGE=ON ^
    -DTLRENDER_NET=%TLRENDER_NET% ^
    -DTLRENDER_OCIO=%TLRENDER_OCIO% ^
    -DTLRENDER_EXR=%TLRENDER_EXR% ^
    -DTLRENDER_AOM=%TLRENDER_AOM% ^
    -DTLRENDER_SVTAV1=%TLRENDER_SVTAV1% ^
    -DTLRENDER_FFMPEG=%TLRENDER_FFMPEG% ^
    -DTLRENDER_FFMPEG_PLUGIN=%TLRENDER_FFMPEG_PLUGIN% ^
    -DTLRENDER_FFMPEG_CMD=%TLRENDER_FFMPEG_CMD% ^
    -DTLRENDER_NASM=%TLRENDER_NASM% ^
    -DTLRENDER_OIIO=%TLRENDER_OIIO% ^
    -DTLRENDER_USD=%TLRENDER_USD% ^
    -Dftk_API=%FTK_API% ^
    -DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS% ^
    -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ^
    -DCMAKE_INSTALL_PREFIX=%CD%/install-%BUILD_TYPE% ^
    -DCMAKE_PREFIX_PATH=%CD%/install-%BUILD_TYPE%
cmake --build build-%BUILD_TYPE% -j %JOBS% --config %BUILD_TYPE%
cmake --build build-%BUILD_TYPE% --config %BUILD_TYPE% --target package

