include(ExternalProject)

set(TLRENDER_GIT_REPOSITORY "https://github.com/grizzlypeak3d/tlRender.git")
set(TLRENDER_GIT_TAG "16df7de0c82013c85d275cbfcc5e406a235d6209")

set(TLRENDER_DEPS)
set(TLRENDER_ARGS
    -DTLRENDER_NET=${TLRENDER_NET}
    -DTLRENDER_OCIO=${TLRENDER_OCIO}
    -DTLRENDER_JPEG=${TLRENDER_JPEG}
    -DTLRENDER_TIFF=${TLRENDER_TIFF}
    -DTLRENDER_EXR=${TLRENDER_EXR}
    -DTLRENDER_SVTAV1=${TLRENDER_SVTAV1}
    -DTLRENDER_FFMPEG=${TLRENDER_FFMPEG}
    -DTLRENDER_FFMPEG_MINIMAL=${TLRENDER_FFMPEG_MINIMAL}
    -DTLRENDER_FFMPEG_PLUGIN=${TLRENDER_FFMPEG_PLUGIN}
    -DTLRENDER_FFMPEG_CMD=${TLRENDER_FFMPEG_CMD}
    -DTLRENDER_NASM=${TLRENDER_NASM}
    -DTLRENDER_OIIO=${TLRENDER_OIIO}
    -DTLRENDER_USD=${TLRENDER_USD}
    -DTLRENDER_USD_PYTHON=${TLRENDER_USD_PYTHON}
    -DTLRENDER_PROGRAMS=OFF
    -DTLRENDER_EXAMPLES=OFF
    -DTLRENDER_TESTS=OFF
    -Dftk_API=${ftk_API}
    ${DJV_EXTERNAL_ARGS})

ExternalProject_Add(
    tl-sb
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/tl-sb
    DEPENDS ${TLRENDER_DEPS}
    GIT_REPOSITORY ${TLRENDER_GIT_REPOSITORY}
    GIT_TAG ${TLRENDER_GIT_TAG}
    INSTALL_COMMAND ""
    SOURCE_SUBDIR etc/SuperBuild
    LIST_SEPARATOR |
    CMAKE_ARGS ${TLRENDER_ARGS})

ExternalProject_Add(
    tl
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/tl
    DEPENDS tl-sb
    GIT_REPOSITORY ${TLRENDER_GIT_REPOSITORY}
    GIT_TAG ${TLRENDER_GIT_TAG}
    LIST_SEPARATOR |
    CMAKE_ARGS ${TLRENDER_ARGS})
