include(ExternalProject)

set(TLRENDER_GIT_REPOSITORY "https://github.com/grizzlypeak3d/tlRender.git")
set(TLRENDER_GIT_TAG "4c1cbe394b6bdfa81e6e7221f0afb59a8c686f54")

set(TLRENDER_DEPS)
set(TLRENDER_ARGS
    -DTLRENDER_NET=${TLRENDER_NET}
    -DTLRENDER_OCIO=${TLRENDER_OCIO}
    -DTLRENDER_JPEG=${TLRENDER_JPEG}
    -DTLRENDER_TIFF=${TLRENDER_TIFF}
    -DTLRENDER_EXR=${TLRENDER_EXR}
    -DTLRENDER_FFMPEG=${TLRENDER_FFMPEG}
    -DTLRENDER_FFMPEG_MINIMAL=${TLRENDER_FFMPEG_MINIMAL}
    -DTLRENDER_OIIO=${TLRENDER_OIIO}
    -DTLRENDER_USD=${TLRENDER_USD}
    -DTLRENDER_USD_PYTHON=${TLRENDER_USD_PYTHON}
    -DTLRENDER_BMD=${TLRENDER_BMD}
    -DTLRENDER_BMD_SDK=${TLRENDER_BMD_SDK}
    -DTLRENDER_PROGRAMS=OFF
    -DTLRENDER_EXAMPLES=OFF
    -DTLRENDER_TESTS=OFF
    -Dftk_API=${ftk_API}
    ${DJV_EXTERNAL_ARGS})

ExternalProject_Add(
    tl-sbuild
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/tl-sbuild
    DEPENDS ${TLRENDER_DEPS}
    GIT_REPOSITORY ${TLRENDER_GIT_REPOSITORY}
    GIT_TAG ${TLRENDER_GIT_TAG}
    INSTALL_COMMAND ""
    SOURCE_SUBDIR etc/SuperBuild
    LIST_SEPARATOR |
    CMAKE_ARGS ${TLRENDER_ARGS})

ExternalProject_Add(
    tlRender
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/tl
    DEPENDS tl-sbuild
    GIT_REPOSITORY ${TLRENDER_GIT_REPOSITORY}
    GIT_TAG ${TLRENDER_GIT_TAG}
    LIST_SEPARATOR |
    CMAKE_ARGS ${TLRENDER_ARGS})
